# profiles group
spring:
  profiles:
    group:
      dev:
        - datadog
        - postgres-local
      prod:
        - datadog
        - tomcat-opt
---
# profile: default
spring:
  application:
    name: SMS
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
    dispatch-options-request: false
server:
  port: 8080
  shutdown: graceful
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
---
# profile: tomcat-optimize
spring:
  config:
    activate:
      on-profile: tomcat-opt

server:
  servlet:
    session:
      timeout: 30m
  tomcat:
    max-connections: 8192
    connection-timeout: 5000
    threads:
      min-spare: 25
      max: 1024
---
# profile: datadog
spring:
  config:
    activate:
      on-profile: datadog
  jmx:
    enable: true

server:
  tomcat:
    mbeanregistry:
      enabled: true
---
# profile postgres-local
spring:
  config:
    activate:
      on-profile: postgres-local
  datasource:
    username: postgres
    password: 1234
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://localhost:5432/postgres